language: python
python: 3.4
install:
  - pip install .
  - pip install -r requirements.txt
script: 
  - nosetests --with-coverage --cover-package=bitpay --cover-html    
  - behave
after_success:
  - coveralls
